# Generated by Django 5.1.7 on 2025-03-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='total_price',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('factor_coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.factorcoefficient')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('quantity', 'تعداد'), ('gram', 'گرم'), ('kilogram', 'کیلوگرم'), ('milliliter', 'میلی لیتر'), ('liter', 'لیتر')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.rawmaterial')),
            ],
        ),
    ]
